export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_LOCATION = "SET_LOCATION";
export const GET_FORECAST_REQUEST = 'GET_FORECAST_REQUEST'
export const GET_FORECAST_SUCCESS = "GET_FORECAST_SUCCESS";
export const GET_FORECAST_FAILURE = 'GET_FORECAST_FAILURE'